### ISSUE TITLE
Custom Checkbox augend

### ISSUE THREAD

**Issue by fallenpixel** [monaqa/dial.nvim#11]
I was attempting to implement an increment/decrement function for a checkbox,
however the following doesn't appear to work the way it does for the true/false
function in the readme. Do the brackets need to be escaped, or am I missing
something different?

```
dial.augends["custom#check"] = dial.common.enum_cyclic{
    name = "check",
    strlist = {"[ ]", "[x]"},
}
```

**Comment by monaqa** [comment]
@fallenpixel Cool idea! Please try the following code.

```
dial.augends["custom#check"] = dial.common.enum_cyclic{
    strlist = {"[ ]", "[x]"},
    ptn_format = [[\C\V\(%s\)]],
}
```

**Comment by fallenpixel** [comment]
Thanks for the code, it certainly works. I noticed the commit about the same time as you made this comment. It looks like you set the default ptn_format to match what you provided here. So this change isn't needed, correct?

**Comment by fallenpixel** [comment]
Commenting for anyone else running into this. After the .3 update this can be accomplished using:
```lua
default = {
  ...
  augend.constant.new{
    elements = {"[ ]", "[x]"}
    word = false,
    cyclic = true,
  }
}
```

**Comment by monaqa** [comment]
> Is there a way to get this to work when the cursor is placed anywhere on the line with the checkbox, and without the cursor jumping?

If you want to customize the behavior in detail, you can use `augend.user` like this:

```lua
dial_config.augends:register_group {
    default = {
        ...,
        augend.user.new {
            find = function(line, cursor)
                if line:find "^%s*%- %[[ x]]" == nil then
                    return
                end
                local checkbox_start = line:find "%["
                return { from = checkbox_start, to = checkbox_start + 2 }
            end,
            add = function(text, addend, cursor)
                if text == "[ ]" then
                    return { text = "[x]" }
                elseif text == "[x]" then
                    return { text = "[ ]" }
                end
                return {}
            end,
        },
    },
}

```

**Comment by monaqa** [comment]
> This still makes the cursor jump, and I have to have the cursor directly over the checkbox for it to work.

No, the settings [I described above](https://github.com/monaqa/dial.nvim/issues/11#issuecomment-3148778108) should solve those problems. If they don't work, then you may not have set them up properly.

**Comment by piersolenski** [comment]
Ah the reason it was failing for me was because I had some other text managed by dial in the todo list item, so it was jumping to that haha.

For example, if I have

```markdown
- [x] It's true that dial is great
```

It will jump to try and toggle true to false, depending on where your cursor is on the line. I don't suppose there's anyway to set a priority so that if I'm anywhere on the line it would toggle the checkbox, but if I'm over the boolean part specifically, it would toggle that?

Sorry, this is quite edge casey 😅

BTW the snippet you pasted has quite a few diagnostic issues for me:

L14:14 [2] Annotations specify that at most 0 return value(s) are required, found 1 returned here instead.
L18:15 [2] Annotations specify that at most 0 return value(s) are required, found 1 returned here instead.
L20:15 [2] Annotations specify that at most 0 return value(s) are required, found 1 returned here instead.
L22:14 [2] Annotations specify that at most 0 return value(s) are required, found 1 returned here instead.
L16:27 [4] Unused local `addend`.
L16:35 [4] Unused local `cursor`.

(Obviously the unused vars issue is easily fixed).
