### ISSUE TITLE
Feature - change quote/brackets - with matching 

### ISSUE THREAD

**Issue by JoseConseco** [monaqa/dial.nvim#14]
I think it would be cool if by changing opening/closing bracket, matching bracket would be changed too e. g.:
test[x]  -  to:  test(x)
Could work on "" and other characters (maybe user defined).

**Comment by monaqa** [comment]
Thank you for your suggestion.

I am wondering if it makes sense to add parenthesis manipulation functionality to dial.nvim now that there are many excellent plugins that specialize in parenthesis manipulation.
For example, [vim-sandwich](https://github.com/machakann/vim-sandwich) is my favorite plugin for these purposes. It's so versatile and can serve most purposes.
Is there anything that can only be accomplished with dial.nvim?

**Comment by JoseConseco** [comment]
The surround plugins are not bad - except, if I do not want to override `s` key and I replace it to <leader>s - then replacing [] with () would be:
<leade>sr[(
Not bad but it takes 5 keys.
With dial it would only take ctrl+a.   Plus it would not break anything since, dial does nothing on ([" '  chars right now.  So it is like new extra feature - that does not have any cons IMO, but it would be cool to have.

**Comment by JoseConseco** [comment]
Hi @monaqa the new bracket and quote feature works great.  It is cool that cursor does not have to be directly on bracket but can be inside of it, and brakcet cycling will work.
I noticed one issue thoug if we have quote inside brackets, like so:
![image](https://user-images.githubusercontent.com/13521338/157896961-37ad6f66-9b3f-4406-ba13-40269863305d.png)
Ten dial will ignore, that cursor is inside quote, and will always change brackets.  Thus in obove case it is impossible to change quote.

**Comment by monaqa** [comment]
@JoseConseco Could I see your configurations?

**Comment by JoseConseco** [comment]
Ok Here is its

```lua
use {  -- increse decrease numbers but also dates, true to false etc
		"monaqa/dial.nvim",
		config = function()
			local augend = require("dial.augend")
			require("dial.config").augends:register_group{
				-- default augends used when no group name is specified
				default = {
					augend.integer.alias.decimal,   -- nonnegative decimal number (0, 1, 2, 3, ...)
					augend.integer.alias.hex,       -- nonnegative hex number  (0x01, 0x1a1f, etc.)
					augend.date.alias["%Y/%m/%d"],  -- date (2022/02/19, etc.)
					augend.constant.alias.bool,
					augend.paren.alias.brackets,
					augend.paren.alias.quote,
					augend.constant.new{
				      elements = {"True", "False"},
				      word = true, -- if false, "sand" is incremented into "sor", "doctor" into "doctand", etc.
				      cyclic = true,  -- "or" is incremented into "and".
				    },
					augend.constant.new{
				      elements = {"==", "!="},
				      word = false, -- if false, "sand" is incremented into "sor", "doctor" into "doctand", etc.
				      cyclic = true,  -- "or" is incremented into "and".
				    },
				},

				-- augends used when group with name `mygroup` is specified
				mygroup = {
					augend.integer.alias.decimal,
					augend.constant.alias.bool,    -- boolean value (true <-> false)
					augend.date.alias["%m/%d/%Y"], -- date (02/19/2022, etc.)
				}
			}
			vim.api.nvim_set_keymap("n", "<C-a>", require("dial.map").inc_normal(), {noremap = true})
			vim.api.nvim_set_keymap("n", "<C-x>", require("dial.map").dec_normal(), {noremap = true})
			vim.api.nvim_set_keymap("v", "<C-a>", require("dial.map").inc_visual(), {noremap = true})
			vim.api.nvim_set_keymap("v", "<C-x>", require("dial.map").dec_visual(), {noremap = true})
			vim.api.nvim_set_keymap("v", "g<C-a>", require("dial.map").inc_gvisual(), {noremap = true})
			vim.api.nvim_set_keymap("v", "g<C-x>", require("dial.map").dec_gvisual(), {noremap = true})
		end,
	}
```

**Comment by monaqa** [comment]
@JoseConseco  Thank you!

It seems an intended behavior.
dial.nvim allows multiple augend rules to be assigned to a single group, and then it is not obvious which rule to use when `<C-a>` / `<C-x>` is actually pressed.
Therefore, the order of precedence is determined based on the range of actual augends. If there are multiple augends under the cursor, the one with the wider range is given higher priority.
In fact, this specification does work well in most cases. For instance, when the cursor is at `3` in `2022/03/12`, the date `2022/03/12` can be incremented or decremented in preference to the number `03`.

In your configuration, both `augend.paren.alias.brackets` and `augend.paren.alias.quote` are in one group. These ranges are as follows:
```
  bl_options = {"REGISTER", "UNDO"}
               ~~~~~~~~~~~~~~~~~~~~     <- range of augend 'brackets'
                ~~~~~~~~~~              <- range of augend 'quote'
```
Because 'brackets' has a larger range than 'quote', 'brackets' always takes precedence over 'quote'.

A possible workaround is to create a group dedicated to `augend.paren.alias.brackets` and `augend.paren.alias.quote`, respectively.

```
require("dial.config").augends:register_group{
  default = {
    ...
  },
  quote = {
    augend.paren.alias.quote,
  },
  bra = {
    augend.paren.alias.brackets,
  },
}
```

In this way, it is possible to "switch only quotes" by typing `"quote<CR><C-a>`.

**Comment by JoseConseco** [comment]
Ok, I did not know that outer scope is more important than inner one (it kind of feels counter-intuitive, but makes sense in date example). I thought I will be able to use same function/mapping for all augend types.  Using different group is ok, but then it takes more typing than vim sandwich (yep I know I can create new mapping - but its not as elegant ).
Is there any chance for you implementing special case behavior - for brackets, and quote - where inner scope  will be more important than outer, without breaking the plugin?

**Comment by monaqa** [comment]
There are currently no plans to change or extend the behavior of the prioritization algorithm. This is because we rarely have trouble with numerical increments or decrements, and we cannot think of a simpler algorithm.
Simple values such as numbers or dates are the main focus of dial.nvim. In contrast, complex objects such as parentheses are not the primary focus. It is not desirable to complicate the overall structure and configuration just for the sake of parentheses manipulation.

To deal with it well within the current framework of dial.nvim, you can define an augend that combines both `brackets` and `quote`:
```lua
  default = {
    ...,
    augend.paren.new {
        patterns = { {"(", ")"}, {"[", "]"}, {"{", "}"}, {"'", "'"}, {'"', '"'} },
        nested = true,
        cyclic = false,
    },
  }
```

If you want more stable and versatile functionality, I still recommend a parentheses-specific plugin.

**Comment by JoseConseco** [comment]
Ok, thanks. Above solution is best workaround. I will close the issue.

**Comment by JoseConseco** [comment]
@monaqa I think I found perfect workaround after all:

```lua
augend.paren.new {
	patterns = { {"(", ")"}, {"[", "]"}, {"{", "}"}, {"(", ")"}, {"'", "'"}, {'"', '"'}, {"'", "'"} },
		nested = true,
		cyclic = false,
	},
```
Adding `(,)` pair twice - forces dial to go cyclic - (, [, {, ( and so on without reaching quotes. Similar trick can be used for ' and ".
